# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_tasklist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tasks', to='todolist.Tag'),
        ),
    ]
