# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20170501_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
