# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0011_auto_20170518_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='friends',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
