# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0012_tasklist_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='friends',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='friends',
            field=models.ManyToManyField(related_name='tasklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
